/** Cities stored exactly as OzonExpress expects (French NAME). */
export type CheckoutCity = { value: string; label: string };

export const CHECKOUT_CITIES: CheckoutCity[] = [
  { value: 'Casablanca – Centre Ville', label: 'الدار البيضاء — وسط المدينة' },
  { value: 'Casablanca – Maarif', label: 'الدار البيضاء — المعاريف' },
  { value: 'Casablanca – Ain Diab', label: 'الدار البيضاء — عين الذئاب' },
  { value: 'Casablanca – Hay Hassani', label: 'الدار البيضاء — الحي الحسني' },
  { value: 'Casablanca – Bernoussi', label: 'الدار البيضاء — البرنوصي' },
  { value: 'Casablanca – Ain Sebaa', label: 'الدار البيضاء — عين السبع' },
  { value: 'Casablanca – Sidi Moumen', label: 'الدار البيضاء — سيدي مومن' },
  { value: 'Casablanca – Oulfa', label: 'الدار البيضاء — الولفة' },
  { value: 'Rabat', label: 'الرباط' },
  { value: 'SALE', label: 'سلا' },
  { value: 'TEMARA', label: 'تمارة' },
  { value: 'KENITRA VILLE', label: 'القنيطرة' },
  { value: 'Mohammedia', label: 'المحمدية' },
  { value: 'Marrakech', label: 'مراكش' },
  { value: 'Fes', label: 'فاس' },
  { value: 'Meknes', label: 'مكناس' },
  { value: 'Tanger', label: 'طنجة' },
  { value: 'Tetouan', label: 'تطوان' },
  { value: 'Agadir', label: 'أكادير' },
  { value: 'Ait Melloul', label: 'أيت ملول' },
  { value: 'Oujda', label: 'وجدة' },
  { value: 'Nador', label: 'الناظور' },
  { value: 'El Jadida', label: 'الجديدة' },
  { value: 'Safi', label: 'آسفي' },
  { value: 'Khouribga', label: 'خريبكة' },
  { value: 'Beni Mellal', label: 'بني ملال' },
  { value: 'BERRECHID VILLE', label: 'برشيد' },
  { value: 'Settate', label: 'سطات' },
  { value: 'Larache', label: 'العرائش' },
  { value: 'Khemisset ville', label: 'الخميسات' },
  { value: 'TAZA-VILLE', label: 'تازة' },
  { value: 'ERRACHIDIA', label: 'الرشيدية' },
];
